### ISSUE TITLE
NamedImageFieldWidget is loosing data after two saves

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.formwidget.namedfile#16]
* Add image.
* Save.
* Open again.
* Save without change.

Setting is losing the image.

**Comment by jensens** [comment]
May you check if this was related to the fix done in #21?

**Comment by thet** [comment]
@rodfersou that should only have happened with NamedImageFieldWidget on an ASCII field, as it was the case with the SiteLogo and also reported here: plone/Products.CMFPlone#1144 and - as @jensens mentioned - fixed with #20.
Please re-check!

**Comment by rodfersou** [comment]
@thet ok I'll take a look today

**Comment by rodfersou** [comment]
@thet @jensens I confirm that your fix close this issue,

Thank you very much.

**Comment by rodfersou** [comment]
a new release would be appreciated
