### ISSUE TITLE
No classes on elements of input templates

### ISSUE THREAD

**Issue by djowett** [plone/plone.formwidget.namedfile#34]
The outer span has classes="named-image-widget namedblobimage-field"
but the inner span and 2 divs have no class at all, which makes it more fiddly to realign than it should be.

If I should make suggestions, here's some:
- span.existing-data
- div.widget-action-choice
- div.change-field

I'm working with 1.0.15 in Plone 4.3

**Comment by gforcada** [comment]
Exactly a day after you posted this @thet simplified the templates 🍀 I think the classes you suggest are missing, but maybe, given the time that passed is not a problem anymore?

Feel free to re-open if you would still like to see this implemented 🤞🏾
