### ISSUE TITLE
Support seekable/skippable video and audio files

### ISSUE THREAD

**Issue by pigeonflight** [plone/plone.formwidget.namedfile#39]
## Rationale
Make it easier to provide seekable video and audio in Plone.

Once video and audio files get longer than 30 seconds it becomes frustrating to be forced to watch an entire video when the viewer only needs to find a 10 second part near the end. By serving video and audio in a "seekable" stream, the widget will support skipping to sections of the a video.

## Proposed implementation
Register a view named `@@seek`.  For a field named "video" it would work almost identically to the `@@download` view. 
```
{absolute_url}/view/++widget++form.widgets.video/@@seek/{filename}
```
The `@@seek` view would be based on the stream view provided by wildcard.media.
see: https://github.com/collective/wildcard.media/blob/master/wildcard/media/browser/widget.py#L30-L58

**Comment by jensens** [comment]
I would like to see this in core!

**Comment by pigeonflight** [comment]
I've started a feature branch for this: https://github.com/plone/plone.formwidget.namedfile/tree/pigeonflight/seek

**Comment by djay** [comment]
Doesn't blobs already support range requests? I'm a little confused why a new view is needed since range requests are about handling special headers in the request right? So can't the normal download view handle it if it doesn't already?

**Comment by jensens** [comment]
Good point. So I have no idea if range requests are supported by the normal download view. But does it help with video, where seek is more about seconds than bytes? (I must admit, I never looked into protocol details here).

**Comment by pbauer** [comment]
Range support is added to plone.amnedfile in https://github.com/plone/plone.namedfile/pull/86
Support in wildcard.media for that is still a TODO.

**Comment by mamico** [comment]
Implementation proposal for Range support (aka seekable/skippable) here https://github.com/plone/plone.formwidget.namedfile/pull/44 (requires plone/plone.namedfile#86)

**Comment by gforcada** [comment]
According to @mamico's comment, both PRs he points out to are merged, should this be considered done then? 🤔 🍀 

Re-open if there's still work to be done 👍🏾
