### ISSUE TITLE
Improve coverage of plone.formwidget.namedfile

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.formwidget.namedfile#5]
_Original author: dgl...@gmail.com (July 20, 2011 03:40:38)_

Feedback from Plone framework team.

&quot;Overall coverage is very good (&gt; 90&#37;),
  with the exception of plone.formwidget.namedfile/widget.py (40&#37;), NamedImage
  and Download class are not under test. Also some helper code in the utils
  files is not tested. I'm not sure all of this code is used, either create
  tests for them or remove the code.&quot;

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=201_

**Comment by jensens** [comment]
outdated
