### ISSUE TITLE
Cleanup runs every 6th time, not 5th as commented

### ISSUE THREAD

**Issue by jensens** [plone/plone.formwidget.namedfile#54]
see
https://github.com/plone/plone.formwidget.namedfile/blob/bfeaf59400a75d95fe0ac43125887589d6aa2a0c/plone/formwidget/namedfile/utils.py#L50-L51

`randint(0, 5)` picks one one out of [0, 1, 2, 3, 4 ,5]

docs at https://docs.python.org/3/library/random.html#random.randint

cc @frisi 

while at it I would make the interval patch-able by introducing a module global `CLEANUP_INTERVAL = 5`

**Comment by frisi** [comment]
you're right @jensens. i copied the docstring w/o thinking about that. 

i don't think it is a big deal whether this happens every 5th or 6th time, but i'll fix it in the existing pr and add a changelog for this issue.
making this patchable is also a good idea.
